import { mkdir, writeFile, copyFile, access, readFile } from 'node:fs/promises';
import c from './content.mjs';
const esc = (s) => String(s).replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const lines = s => esc(s).replace(/\n/g, '<br> ');
const link = (url) => { if (!/^(https:\/\/|mailto:|#|\/)/.test(url) || url.startsWith('//')) throw new Error('Use an https, mailto, anchor, or local URL: '+url); return esc(url); };
const arrow = '<span aria-hidden="true">↗</span>';
const nav = c.navigation.map(n => `<a href="#${esc(n.id)}"${n.id==='get-involved'?' class="nav-action"':''}>${esc(n.label)}${n.id==='get-involved'?arrow:''}</a>`).join('');
const gallery = c.gallery.images.length ? `<div class="photo-journal">${c.gallery.images.map((p,i) => { if(!p.alt || !p.width || !p.height || !p.caption) throw new Error('Photos need alt, caption, width and height'); return `<figure><button class="photo-trigger" data-photo="${i}" aria-label="${esc(c.accessibility.openPhoto)}: ${esc(p.caption)}"><img src="${link(p.src)}" alt="${esc(p.alt)}" width="${p.width}" height="${p.height}" loading="lazy" decoding="async"></button><figcaption><span>${String(i+1).padStart(2,'0')}</span>${esc(p.caption)}</figcaption></figure>`; }).join('')}</div>` : `<div class="journal-empty"><span class="journal-rule" aria-hidden="true"></span><p>${esc(c.gallery.empty)}</p></div>`;
const socials = c.contact.socials.map(s => `<a class="text-link" href="${link(s.url)}">${esc(s.label)} ${arrow}</a>`).join('');
const f = c.contact.form;
const contactForm = `<form id="contact-form" class="message-form" action="${link(f.action)}" method="POST" data-endpoint="${link(f.endpoint)}" data-success="${esc(f.success)}" data-error="${esc(f.error)}" data-inactive="${esc(f.inactive)}" data-invalid="${esc(f.invalid)}" data-sending="${esc(f.sending)}" data-submit="${esc(f.submit)}">
<input type="hidden" name="_subject" value="${esc(f.subject)}"><input type="hidden" name="_template" value="table"><input class="form-honeypot" type="text" name="_honey" tabindex="-1" autocomplete="off" aria-hidden="true">
<div class="form-row"><div class="form-field"><label for="contact-name">${esc(f.nameLabel)}</label><input id="contact-name" name="name" type="text" autocomplete="name" required maxlength="100"></div><div class="form-field"><label for="contact-email">${esc(f.emailLabel)}</label><input id="contact-email" name="email" type="email" autocomplete="email" required maxlength="254"></div></div>
<div class="form-field"><label for="contact-message">${esc(f.messageLabel)}</label><textarea id="contact-message" name="message" required maxlength="5000" rows="6" placeholder="${esc(f.messagePlaceholder)}"></textarea></div>
<div class="form-submit-row"><button class="button" type="submit"><span class="submit-label">${esc(f.submit)}</span><span aria-hidden="true">↗</span></button><p class="form-note">${esc(f.requiredNote)}</p></div>
<p id="form-status" class="form-status" role="status" aria-live="polite" tabindex="-1" hidden></p><p class="provider-note">${esc(f.providerNote)} <a href="${link(f.providerUrl)}">${esc(f.providerName)}</a>.</p></form>`;
const html = `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f8f6f2"><title>${esc(c.meta.title)}</title><meta name="description" content="${esc(c.meta.description)}"><meta property="og:title" content="${esc(c.meta.title)}"><meta property="og:description" content="${esc(c.meta.description)}"><meta property="og:type" content="website"><link rel="icon" type="image/png" href="/assets/kanto-logo.png"><link rel="preload" href="/assets/fonts/fraunces.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/dm-sans.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head>
<body id="top"><a class="skip-link" href="#main">${esc(c.accessibility.skip)}</a>
<header class="site-header"><div class="header-inner wrap"><a class="brand" href="#top" aria-label="${esc(c.accessibility.home)}"><img src="/assets/kanto-logo.png" width="500" height="500" alt="${esc(c.name)}" fetchpriority="high"></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" data-open="${esc(c.accessibility.menu)}" data-close="${esc(c.accessibility.closeMenu)}" hidden>${esc(c.accessibility.menu)} <span aria-hidden="true">+</span></button><nav id="main-nav" aria-label="${esc(c.accessibility.navigation)}">${nav}</nav></div></header>
<main id="main"><section class="hero wrap" aria-labelledby="hero-heading"><p class="eyebrow hero-eyebrow">${esc(c.hero.eyebrow)}</p><h1 id="hero-heading"><span>${esc(c.hero.lines[0])}</span><em>${esc(c.hero.lines[1])}</em></h1><div class="hero-bottom"><div class="hero-actions"><a class="button" href="#get-involved">${esc(c.hero.primary)} <span aria-hidden="true">↗</span></a><a class="text-link" href="#our-story">${esc(c.hero.secondary)} <span aria-hidden="true">↓</span></a></div><p class="hero-description">${esc(c.hero.description)}</p></div><p class="hero-footnote">${esc(c.hero.footnote)}</p></section>
<section id="our-story" class="story section wrap" aria-labelledby="story-heading"><div class="section-label">${esc(c.story.label)}</div><div class="story-grid"><div class="story-copy"><h2 id="story-heading">${lines(c.story.heading)}</h2>${c.story.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div><aside class="impact" aria-label="${esc(c.impact.label)}"><p class="impact-number">${esc(c.impact.value)}</p><p class="impact-label">${esc(c.impact.label)}</p>${c.impact.asOf?`<p class="impact-date">${esc(c.impact.asOf)}</p>`:''}<p class="milestone">${esc(c.story.milestone)}</p></aside></div></section>
<section id="in-pictures" class="pictures section wrap" aria-labelledby="pictures-heading"><div class="section-label">${esc(c.gallery.label)}</div><div class="pictures-intro"><h2 id="pictures-heading">${lines(c.gallery.heading)}</h2>${c.gallery.images.length?'':gallery}</div>${c.gallery.images.length?gallery:''}</section>
<section id="get-involved" class="involvement section" aria-labelledby="contact-heading"><span id="say-hello" class="anchor-alias" aria-hidden="true"></span><div class="wrap"><div class="section-label">${esc(c.contact.label)}</div><div class="message-layout"><div class="message-intro"><h2 id="contact-heading">${lines(c.contact.heading)}</h2><p>${esc(c.contact.description)}</p></div><div class="message-column">${contactForm}<div class="contact-alternatives"><p><span>${esc(c.contact.emailLead)}</span><a href="mailto:${esc(c.contact.email)}">${esc(c.contact.email)} ${arrow}</a></p>${c.contact.socials.map(s=>`<p><span>${esc(c.contact.socialLead)}</span><a href="${link(s.url)}">${esc(s.label)} ${arrow}</a><span>${esc(c.contact.socialSuffix)}</span></p>`).join('')}</div></div></div></div></section></main>
<footer class="site-footer"><div class="wrap"><div class="footer-top"><div><p class="footer-name">${esc(c.name)}</p><p class="footer-mission">${esc(c.footer.mission)}</p></div><div class="footer-links">${socials}<a href="#top" class="back-top">${esc(c.footer.backToTop)} <span aria-hidden="true">↑</span></a></div></div><div class="footer-bottom"><p>© ${c.footer.copyrightYear} ${esc(c.name)}</p><p>${esc(c.footer.designation)}</p></div></div></footer>
${c.gallery.images.length?`<dialog class="lightbox" aria-label="${esc(c.accessibility.photoDialog)}"><div class="lightbox-toolbar"><span class="photo-count" aria-live="polite"></span><button class="close-photo" aria-label="${esc(c.accessibility.closePhoto)}">${esc(c.accessibility.closeMenu)} ×</button></div><figure><img class="lightbox-image" alt=""><figcaption class="lightbox-caption" aria-live="polite"></figcaption></figure><div class="lightbox-controls"><button class="previous-photo" aria-label="${esc(c.accessibility.previousPhoto)}">←</button><button class="next-photo" aria-label="${esc(c.accessibility.nextPhoto)}">→</button></div></dialog><script type="application/json" id="gallery-data">${JSON.stringify(c.gallery.images).replace(/</g,'\\u003c')}</script>`:''}
</body></html>`;
await mkdir('dist', {recursive:true});
const styles = await Promise.all(['src/styles.css','src/contact.css'].map(p=>readFile(p,'utf8')));
await Promise.all([writeFile('dist/index.html',html),writeFile('dist/styles.css',styles.join('\n')),copyFile('src/app.js','dist/app.js')]);
for(const path of ['dist/assets/kanto-logo.png','dist/assets/fonts/fraunces.woff2','dist/assets/fonts/fraunces-italic.woff2','dist/assets/fonts/dm-sans.woff2']) await access(path);
console.log('Built The Kanto Project: static HTML, CSS, and JavaScript.');
