import { mkdir, writeFile, copyFile, access } from 'node:fs/promises';
import c from './content.mjs';
const esc = (s) => String(s).replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const lines = s => esc(s).replace(/\n/g, '<br> ');
const link = (url) => { if (!/^(https:\/\/|mailto:|#|\/)/.test(url) || url.startsWith('//')) throw new Error('Use an https, mailto, anchor, or local URL: '+url); return esc(url); };
const arrow = '<span aria-hidden="true">↗</span>';
const nav = c.navigation.map(n => `<a href="#${esc(n.id)}"${n.id==='get-involved'?' class="nav-action"':''}>${esc(n.label)}${n.id==='get-involved'?arrow:''}</a>`).join('');
const gallery = c.gallery.images.length ? `<div class="photo-journal">${c.gallery.images.map((p,i) => { if(!p.alt || !p.width || !p.height || !p.caption) throw new Error('Photos need alt, caption, width and height'); return `<figure><button class="photo-trigger" data-photo="${i}" aria-label="${esc(c.accessibility.openPhoto)}: ${esc(p.caption)}"><img src="${link(p.src)}" alt="${esc(p.alt)}" width="${p.width}" height="${p.height}" loading="lazy" decoding="async"></button><figcaption><span>${String(i+1).padStart(2,'0')}</span>${esc(p.caption)}</figcaption></figure>`; }).join('')}</div>` : `<div class="journal-empty"><span class="journal-rule" aria-hidden="true"></span><p>${esc(c.gallery.empty)}</p></div>`;
const cardUrl = c.involvement.cards.url || (c.contact.email ? `mailto:${c.contact.email}?subject=Card%20donation` : '');
const donate = (kind,number,url) => `<article class="giving-option"><span class="option-number" aria-hidden="true">${number}</span><div><h3>${esc(kind.title)}</h3><p>${esc(kind.description)}</p>${kind.details?`<p>${esc(kind.details)}</p>`:''}${url?`<a class="text-link" href="${link(url)}">${esc(kind.action)} ${arrow}</a>`:`<p class="availability">${esc(kind.pending)}</p>`}</div></article>`;
const socials = c.contact.socials.map(s => `<a class="text-link" href="${link(s.url)}">${esc(s.label)} ${arrow}</a>`).join('');
const html = `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f8f6f2"><title>${esc(c.meta.title)}</title><meta name="description" content="${esc(c.meta.description)}"><meta property="og:title" content="${esc(c.meta.title)}"><meta property="og:description" content="${esc(c.meta.description)}"><meta property="og:type" content="website"><link rel="icon" type="image/png" href="/assets/kanto-logo.png"><link rel="preload" href="/assets/fonts/fraunces.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/dm-sans.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head>
<body id="top"><a class="skip-link" href="#main">${esc(c.accessibility.skip)}</a>
<header class="site-header"><div class="header-inner wrap"><a class="brand" href="#top" aria-label="${esc(c.accessibility.home)}"><img src="/assets/kanto-logo.png" width="500" height="500" alt="${esc(c.name)}" fetchpriority="high"></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" data-open="${esc(c.accessibility.menu)}" data-close="${esc(c.accessibility.closeMenu)}" hidden>${esc(c.accessibility.menu)} <span aria-hidden="true">+</span></button><nav id="main-nav" aria-label="${esc(c.accessibility.navigation)}">${nav}</nav></div></header>
<main id="main"><section class="hero wrap" aria-labelledby="hero-heading"><p class="eyebrow hero-eyebrow">${esc(c.hero.eyebrow)}</p><h1 id="hero-heading"><span>${esc(c.hero.lines[0])}</span><em>${esc(c.hero.lines[1])}</em></h1><div class="hero-bottom"><div class="hero-actions"><a class="button" href="#get-involved">${esc(c.hero.primary)} <span aria-hidden="true">↗</span></a><a class="text-link" href="#our-story">${esc(c.hero.secondary)} <span aria-hidden="true">↓</span></a></div><p class="hero-description">${esc(c.hero.description)}</p></div><p class="hero-footnote">${esc(c.hero.footnote)}</p></section>
<section id="our-story" class="story section wrap" aria-labelledby="story-heading"><div class="section-label">${esc(c.story.label)}</div><div class="story-grid"><div class="story-copy"><h2 id="story-heading">${lines(c.story.heading)}</h2>${c.story.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div><aside class="impact" aria-label="${esc(c.impact.label)}"><p class="impact-number">${esc(c.impact.value)}</p><p class="impact-label">${esc(c.impact.label)}</p><p class="impact-date">${esc(c.impact.asOf)}</p><p class="milestone">${esc(c.story.milestone)}</p></aside></div></section>
<section id="in-pictures" class="pictures section wrap" aria-labelledby="pictures-heading"><div class="section-label">${esc(c.gallery.label)}</div><div class="pictures-intro"><h2 id="pictures-heading">${lines(c.gallery.heading)}</h2>${c.gallery.images.length?'':gallery}</div>${c.gallery.images.length?gallery:''}</section>
<section id="get-involved" class="involvement section" aria-labelledby="involvement-heading"><div class="wrap"><div class="section-label">${esc(c.involvement.label)}</div><h2 id="involvement-heading">${lines(c.involvement.heading)}</h2><div class="giving-options">${donate(c.involvement.cards,'01',cardUrl)}${donate(c.involvement.financial,'02',c.involvement.financial.url)}</div></div></section>
<section id="say-hello" class="hello section wrap" aria-labelledby="hello-heading"><div class="section-label">${esc(c.contact.label)}</div><div class="hello-grid"><h2 id="hello-heading">${lines(c.contact.heading)}</h2><div><p>${esc(c.contact.description)}</p><div class="contact-links">${c.contact.email?`<a class="text-link" href="mailto:${esc(c.contact.email)}">${esc(c.contact.email)} ${arrow}</a>`:`<p class="availability">${esc(c.contact.pending)}</p>`}${socials}</div></div></div></section></main>
<footer class="site-footer"><div class="wrap"><div class="footer-top"><div><p class="footer-name">${esc(c.name)}</p><p class="footer-mission">${esc(c.footer.mission)}</p></div><a href="#top" class="back-top">${esc(c.footer.backToTop)} <span aria-hidden="true">↑</span></a></div><div class="footer-bottom"><p>© ${c.footer.copyrightYear} ${esc(c.name)}</p><p>${esc(c.footer.designation)}</p></div></div></footer>
${c.gallery.images.length?`<dialog class="lightbox" aria-label="${esc(c.accessibility.photoDialog)}"><div class="lightbox-toolbar"><span class="photo-count" aria-live="polite"></span><button class="close-photo" aria-label="${esc(c.accessibility.closePhoto)}">${esc(c.accessibility.closeMenu)} ×</button></div><figure><img class="lightbox-image" alt=""><figcaption class="lightbox-caption" aria-live="polite"></figcaption></figure><div class="lightbox-controls"><button class="previous-photo" aria-label="${esc(c.accessibility.previousPhoto)}">←</button><button class="next-photo" aria-label="${esc(c.accessibility.nextPhoto)}">→</button></div></dialog><script type="application/json" id="gallery-data">${JSON.stringify(c.gallery.images).replace(/</g,'\\u003c')}</script>`:''}
</body></html>`;
await mkdir('dist', {recursive:true});
await Promise.all([writeFile('dist/index.html',html),copyFile('src/styles.css','dist/styles.css'),copyFile('src/app.js','dist/app.js')]);
for(const path of ['dist/assets/kanto-logo.png','dist/assets/fonts/fraunces.woff2','dist/assets/fonts/fraunces-italic.woff2','dist/assets/fonts/dm-sans.woff2']) await access(path);
console.log('Built The Kanto Project: static HTML, CSS, and JavaScript.');
