import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const source=await readFile('src/app.js','utf8');
const fn=source.slice(source.indexOf('function classifyFormResponse'),source.indexOf("const dialog ="));
const classify=vm.runInNewContext(`(${fn.trim()})`);
assert.equal(classify(true,{success:'false',message:'This form needs Activation.'}),'inactive');
assert.equal(classify(true,{success:'true',message:'Please activate your form'}),'inactive');
assert.equal(classify(true,{success:'true',message:'Form successfully submitted'}),'success');
assert.equal(classify(true,{success:true}),'success');
assert.equal(classify(false,{success:true}),'error');
assert.equal(classify(true,{success:'false'}),'error');
assert.equal(classify(true,{}),'error');
assert.equal(classify(true,null),'error');
const html=await readFile('dist/index.html','utf8');
assert.match(html,/25,000/);assert.doesNotMatch(html,/15,000|As of August 2026|04 \/ Say Hello|A shared love\. A new beginning|For the love of collecting|Our work includes a completed card donation|the cards you love/);
assert.match(html,/A new home for/);assert.match(html,/the bulk you don’t want/);
assert.match(html,/https:\/\/formsubmit.co\/ajax\/contact@thekantoproject.org/);
assert.match(html,/mailto:contact@thekantoproject.org/);
assert.match(html,/https:\/\/www.instagram.com\/thekantoproject\//);
assert.equal((html.match(/<form /g)||[]).length,1);
const photos=await readFile('dist/photos.html','utf8');
assert.match(html,/href="photos\.html"[^>]*>View our photo album/);
assert.match(photos,/Our photo album/);assert.match(photos,/This album is empty for now/);assert.match(photos,/index\.html#in-pictures/);
console.log('Contact response handling, merged section, impact, and destinations passed.');
